SELECT RI.FOOD_TYPE,RI.REST_ID,RI.REST_NAME,RI.FAVORITES
FROM    REST_INFO RI,
        (SELECT MAX(FAVORITES) AS FAVORITES,FOOD_TYPE
        FROM   REST_INFO
        GROUP BY FOOD_TYPE) BT
WHERE   RI.FOOD_TYPE = BT.FOOD_TYPE
AND     RI.FAVORITES = BT.FAVORITES
ORDER BY RI.FOOD_TYPE DESC