-- 코드를 입력하세요
SELECT CAR_ID,ROUND(AVG(END_DATE-START_DATE),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE END_DATE - START_DATE  >= 7
GROUP BY CAR_ID
HAVING AVG(END_DATE-START_DATE)>=7
ORDER BY AVG(END_DATE-START_DATE) DESC, CAR_ID DESC